version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: rewards_api/Dockerfile
    image: local/rewards_api:api
    command: ['python3', 'manage.py', 'runserver', '0.0.0.0:8000']
    restart: always
    volumes:
      - ./rewards_api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    image: local/rewards_api:api
    command: [ "celery", "-A", 'api', "worker", '-l', 'info', '-E', "-Q", "celery" ]
    restart: always
    volumes:
      - ./rewards_api:/app
    depends_on:
      - db
      - redis

  populate:
    image: local/rewards_api:api
    command: [ "python3", "manage.py", "populate", "--create-superuser" ]
    restart: on-failure
    volumes:
      - ./rewards_api:/app
    depends_on:
      - db
      - redis

  migrations:
    image: local/rewards_api:api
    command: ["python3", "manage.py", "migrate", "--no-input" ]
    restart: on-failure
    volumes:
      - ./rewards_api:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"


