# Generated by Django 5.2 on 2025-04-14 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_scheduledreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
