# Generated by Django 5.2 on 2025-04-14 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rewardlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRewardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User reward request',
                'verbose_name_plural': 'User reward requests',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
